/**
 * An Account which a Transaction may add or remove funds from.
 */
export class Account {
  /**
   * Unique account ID.
   *
   * Generated by CMS.
   */
  id: number;

  /**
   * Name of account.
   *
   * [TODO] Should not need to be unique, but current implementation relies on unique assumption. Whoops.
   */
  name: string;

  /**
   * Details, notes, or description of account.
   */
  details: string | null;

  /**
   * Account type.
   */
  type: 'checking' | 'savings' | 'credit' | 'loan' | null;

  /**
   * Account starting balance which Transaction credits and debits are applied against.
   */
  initialBalance: number;
}

/**
 * Concept for categorizing and tracking spend.
 */
export class Bucket {
  /**
   * Unique bucket ID.
   *
   * Generated by CMS.
   */
  id: number;

  /**
   * Name of bucket.
   *
   * [TODO] Should not need to be unique; unfortunately, current implemntation relies on unique assumption. Dang.
   */
  name: string;
}

/**
 * A transaction which has not yet been submitted to API and assigned an ID.
 */
export class PendingTransaction {
  /**
   * Short name for the transaction.
   */
  name: string;

  /**
   * Value of the transaction.
   */
  amount: number;

  /**
   * Details, notes, or description of the transaction.
   */
  details: string;

  /**
   * Date the transaction is due.
   */
  due: string;

  /**
   * Date the transaction is/was scheduled/for.
   */
  scheduled: string;

  /**
   * Date the transcation is/was effective.
   */
  effective: string;

  /**
   * Account from which the transaction value is deducted.
   */
  fromAccount: any;

  /**
   * Account to which the transaction value is added.
   */
  toAccount: any;

  /**
   * Tracking bucket that the transaction should belong to.
   */
  bucket: any;
}

/**
 * A transaction which already exists in the CMS and has an ID.
 */
export class Transaction extends PendingTransaction {
  /**
   * Unique transaction ID.
   *
   * Generated by CMS.
   */
  id: number;

  /**
   * Date last updated as reported by CMS.
   */
  updated_at?: string;

  /**
   * Date created as reported by CMS.
   */
  created_at?: string;
}
